server:
  port: 8090

spring:
  datasource:
      username: root
      password: admin
      url: jdbc:mysql://127.0.0.1:3306/spring-security-oauth2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 8
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL

logging:
  level:
    com.tca.security.oauth2.web.mapper: debug